name: "Legitify Analyze"
description: "Legitify GitHub Action"
branding:
  color: "purple"
  icon: "target"
inputs:
  github_token:
    description: "GitHub Personal Access Token"
    required: true
  analyze_self_only:
    description: "If this is set, only the repo where this action is called from will be analyzed"
    required: false
    default: "false"
  repositories:
    description: "Strings of owner/repo. If this is set, only selected repositories will be analyzed"
    required: false
  legitify_base_version:
    description: "The base version of legitify to use. Non breaking changes will be auto updated."
    required: false
    default: "0.2"
  scorecard:
    description: 'Whether to run scorecard as part of the analysis (no/yes/verbose default to "no")'
    required: false
    default: "no"
  sarif:
    description: 'Whether to output results in SARIF format and upload them to the Security Center'
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Set Up NodeJS
      uses: actions/setup-node@v3
      with:
          node-version: '16'
    - name: "Check out Legitify"
      uses: actions/checkout@v2
    - name: "Run Legitify"
      uses: shell 
      run: |
        node index.js
    - name: "Upload SARIF results"
      if: inputs.sarif == 'true'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif